### PR TITLE
Feature/reduce api calls

### PR DESCRIPTION
**Pull request by StefanoChiodino**
Hi @warrenbuckley, I've changed YouTube to SimpleYouTube since it's a breaking change and wrapped just the same elements that are in the DB. #25

### CODE REVIEW

**Comment by StefanoChiodino** [comment]
Hi @warrenbuckley, any news?

**Comment by warrenbuckley** [comment]
Hi @StefanoChiodino sorry been busy & my sideline projects have been neglected.
What does this do or try to solve, then I can try & take a look at merging it in

**Comment by StefanoChiodino** [comment]
No worries @warrenbuckley, It changes what is returned from the property to be exactly what is stored in the DB (id and title of video). This way the frontend of the website doesn't make API calls and won't break if above quota. I've change the name of the type to hopefully make it clearer to the good folks updating that this is a breaking change.

**Comment by samgooch** [comment]
Can we have this merged in if it's acceptable?

**Comment by jobf** [comment]
Another request for getting this merged in if possible :)

Thanks!

**Pull request merged**
