### PR TITLE
Allow API key to be overridden in web.config

### LINKED ISSUE #19: Youtube Quota reached
```
Google.Apis.Requests.RequestError
The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>. [403]
Errors [
Message[The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.] Location[ - ] Reason[quotaExceeded] Domain[youtube.quota]
]

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Google.GoogleApiException: Google.Apis.Requests.RequestError
The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>. [403]
Errors [
Message[The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.] Location[ - ] Reason[quotaExceeded] Domain[youtube.quota]
]

```

When the Youtube quota is reached, this plugin fails when attempting to find a video:

`foreach (var typedVideo in Model.Content.GetPropertyValue<YouTube>("video").Take(1))`

This causes the page to fail to load.

### PR DESCRIPTION
**Pull request by ryanlewis**
Allows configurable API key in the web.config.

Add the following to your web.config file:

```
<appSettings>
  <add key="YouTube-Video:ApiKey" value="<APIKEY>" />
</appSettings>

### CODE REVIEW

**Comment by ryanlewis** [comment]
Resolves #19

**Comment by warrenbuckley** [comment]
Thanks your a legend @ryanlewis ❤️ 👍 
Been mega busy & dropped the ball on this clearly. Still surprised it was using a shared key. Someone clearly hammering the API somewhere but anyway thanks for fixing it. I owe you a beer or two at CodeGarden :)

**Comment by ryanlewis** [comment]
Employee won't send me, but happy to take up you another time! 😊

-- 
Ryan Lewis

From: Warren Buckley <notifications@github.com> <notifications@github.com>
Reply: warrenbuckley/YouTube-Umbraco
<reply@reply.github.com>
<reply@reply.github.com>
Date: 21 April 2016 at 20:32:24
To: warrenbuckley/YouTube-Umbraco <youtube-umbraco@noreply.github.com>
<youtube-umbraco@noreply.github.com>
CC: Ryan Lewis <ryan@wpyz.org> <ryan@wpyz.org>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [warrenbuckley/YouTube-Umbraco] Allow API key to be
overridden in web.config (#20)

Thanks your a legend @ryanlewis <https://github.com/ryanlewis> ❤️ 👍

**Comment by warrenbuckley** [comment]
What well your boss is nuts, then at the next UKFest or hackathon then I'll buy you a beer @ryanlewis 

Now published to Nuget as 1.0.4
https://www.nuget.org/packages/YouTube.Umbraco/1.0.4

Will upload the ZIP to our.umb now but artifacts here
https://ci.appveyor.com/project/warrenbuckley/youtube-umbraco/build/artifacts

**Comment by Jeavon** [comment]
Totally nuts! Great job @ryanlewis

**Pull request merged**
